### ISSUE TITLE
Date formating for last_seen does not respect system date/time format.

### ISSUE THREAD

**Issue by Rayman2200** [AaronTraas/Clash-Royale-Clan-Tools#43]
Hi Aaron,
the fix for #40 cause a chain of new bugs regarding the date/time formating.
See https://polska.clash-royal.tk/ 

The "Date Inactive" row shows always 0

I think it is a parsing error at this line

https://github.com/AaronTraas/Clash-Royale-Clan-Tools/blob/7a3e686378c1c66313d4cbb5c2c7675420c19339/crtools/crtools.py#L266

Maybe there are more errors.

Best regards 
Thomas

**Comment by AaronTraas** [comment]
You misunderstand. Days inactive isn't the same as last seen. If you click on an individual user, like so:

<img width="722" alt="Screen Shot 2019-09-11 at 1 59 36 PM" src="https://user-images.githubusercontent.com/1229439/64722515-9a496a00-d49c-11e9-823f-bef839f502d0.png">

You see that days inactive and last seen are two different values.

Days inactive is the number of days since an activity event happened. Those events are:

- joined clan
- left clan
- donation
- did something in war

Whilst last seen was the last time they logged in, and is returned by the API.

Since you just ran this for the first time recently, everyone's last activity and last donation date is going to be at the time of first run. See:

https://polska.clash-royal.tk/history.json

Note that each user has a `last_activity_date` and `last_donation_date` -- those are recorded and calculated each time the application runs over time. If the user donated since the last run, the `last_donation_date` is reset to now. Likewise with joining a war and `last_activity_date`.

Why do I do it this way? Because the API doesn't give me the information. It only provides, for the most part, the current state, not past actions.

**Comment by AaronTraas** [comment]
BTW, the relevant code is here:

https://github.com/AaronTraas/Clash-Royale-Clan-Tools/blob/7a3e686378c1c66313d4cbb5c2c7675420c19339/crtools/history.py#L190-L195

**Comment by Rayman2200** [comment]
That makes sense. But what I don't understand is, that I start running this script yesterday and copied the generated page to my root server. So I thought the "last activity" would be the same as last seen or older.

We have some players like (Poll) that is inactive for about 3 weeks. So I was wondering, why he has an last activity of today.. 

I also started deliberate on how the history.json works :) so each script execution will incrementally update the history. Can something happen if I generate the history on a machine with a different locale / date / time system, like I do yesterday?

Never mind, I would like to thank you for your help and this awesome dashboard.

**Comment by AaronTraas** [comment]
If you delete the folder every time, then the history will never update. It will be as if it was always newly created.

If you run it on one machine, preserving the original directory, then upload to another, you're fine. You do want to keep the history.json file around on the machine you're running crtools.

**Comment by AaronTraas** [comment]
@Rayman2200 Feel free to join the discord if you need further help. Also, if you want, I'd welcome a Polish translation. Look in https://github.com/AaronTraas/Clash-Royale-Clan-Tools/tree/master/crtools/locale -- we're already available in French, German, and Chinese.
