### ISSUE TITLE
Store within a Db

### ISSUE THREAD

**Issue by hunch-13** [AaronTraas/Clash-Royale-Clan-Tools#62]
Just found this project, love it so far.

Wondering if you've ever considered storing in a mysql db vs json?  Would allow "us" to store far more local data which could then be manipulated easier.  This could also allow tie in to discord bots and such.  (I've seen  how you've implemented discord webhooks, I could potentially write a bot pulling data from mysql).

**Comment by AaronTraas** [comment]
If you want to modify to use a MySQL backend, go for it. I'm personally not interested; I wanted this to be entirely static, with the only state maintained being the JSON file. I don't run a DB on my server, and would prefer to keep it that way.

**Comment by hunch-13** [comment]
I don't likely have the skills likely, was just a suggestion to open up more options/flexibility.  

doesn't it already store in json though for history (so not exactly static?)

**Comment by AaronTraas** [comment]
Yes, it stores all the state in the history. The point is, it runs as a batch, on my server, once per hour, and generates the static HTML from the JSON file and results of the incoming API. But it does not require running a database, so my server can be dumber. In fact, in my configuration, it runs on a non-public application server that basically only runs cron jobs, then sends it via SFTP to a dumber server running nothing but SSH and nginx, which only serves up static pages. 

I'm personally uninterested in the configuration you want for my own needs.

Why do you need the history data in MySQL in order to write a bot? Can't your bot consume the contents of history.json? Parsing JSON in most modern languages is pretty trivial, actually moreso than connecting to a DB.

**Comment by hunch-13** [comment]
I get you aren't interested/doesn't fit your use.  It was simply an enhancement suggestion , not a demand or anything . sorry if you saw it that way 

history.json file is limited , its not a real history exactly.  Eg I can see donations for player A for this week and last, but can't see l, 2 weeks ago , 3 + , to average etc.  Parsing JSON isn't the issue, its the limited info (for some things I was thinking) , joins/leaves etc aren't tracked though I see there is a view old memebers button , unsure where it pulls info from.

its no biggie and appreciate finding this.

**Comment by AaronTraas** [comment]
Gotcha -- no worries.

I'm only storing the history that makes sense for rendering the page and evaluating a user in our scoring system. Because it's not a DB, I care about the file size and speed of parsing. 

Also, joins/leaves can't really be tracked. The API doesn't provide that data. I infer it based on the "events" section of each person. The first instance of a member being present, I count as a join. If they disappear, I count that as a quit. Impossible to know whether they were kicked or quit or not.

As far as where the old users are -- they're in the history. The members list contain all members that the application has ever observed. There's no way to get that data from the API; the only way to get it is to track over time who is in your clan. Note that there are more than 50 members in the members list of the history.json: https://agrassar.com/history.json

For instance:
```
        "#8CL8989L": {
            "join_date": 0,
            "role": "coLeader",
            "status": "present",
            "events": [
                {
                    "event": "join",
                    "type": "new",
                    "role": "leader",
                    "date": 0
                },
                {
                    "event": "quit",
                    "type": "left",
                    "role": "leader",
                    "date": 1563207421.553984
                },
                {
                    "event": "join",
                    "type": "re-join",
                    "role": "coLeader",
                    "date": 1574104648.037579
                },
                {
                    "event": "quit",
                    "type": "left",
                    "role": "coLeader",
                    "date": 1579591025.850908
                },
                {
                    "event": "join",
                    "type": "re-join",
                    "role": "coLeader",
                    "date": 1584332227.528739
                },
                {
                    "event": "quit",
                    "type": "left",
                    "role": "coLeader",
                    "date": 1587493028.325769
                },
                {
                    "event": "join",
                    "type": "re-join",
                    "role": "coLeader",
                    "date": 1593296227.568151
                }
            ],
            "last_activity_date": 1605057428.798261,
            "last_donation_date": 1605057428.798261,
            "donations": 0,
            "donations_last_week": 18,
            "name": "Birdicus"
        },
```
That's a member that has joined and left multiple times.

**Comment by hunch-13** [comment]
yah I see how that works now in the file.  I understand the api doesn't give it directly.  What happens if someone leaves, but then rejoins?  History file likely wouldn't show it I assume, again no biggie.  It could be tracked indirectly like how royalapi does it but might be a pain

**Comment by AaronTraas** [comment]
It does show it. Look at the above. I have events for "left" and "re-join".

It works by again, checking every hour. If a person who was listed as present is not, we see that, and create a "left" event. If in the future they re-join, we see that they are present, we look them up in history and create a "re-join" event. It's all tied to their user tag, which is the key in the members the dictionary.
